DROP DATABASE BD_GO_ECHO;
CREATE DATABASE BD_GO_ECHO;
USE BD_GO_ECHO;

CREATE TABLE tb_users(
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    email VARCHAR(30) NOT NULL,
    pass VARCHAR(50) NOT NULL
);

CREATE TABLE tb_courses(
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(30) NOT NULL,
    active bool DEFAULT FALSE NOT NULL,
    teacher VARCHAR(20)
);
